version: '3.8'

services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.frontend
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    environment:
      - PORT=${FRONTEND_PORT}
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.5"

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.backend
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      - BACKEND_PORT=${BACKEND_PORT}
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.5"
